export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const ADD_TO_TEMP_BILL_SUCCESS = 'ADD_TO_TEMP_BILL_SUCCESS'
export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS'
export const GET_ALL_PRODUCTS_FAIL = 'GET_ALL_PRODUCTS_FAIL'
export const CHANGE_QUANTITY_IN_TEMP_BILL_SUCCESS = 'CHANGE_QUANTITY_IN_TEMP_BILL_SUCCESS'
export const ADD_NEW_PRODUCT_SUCCESS = 'ADD_NEW_PRODUCT_SUCCESS'
export const ADD_NEW_PRODUCT_FAIL = 'ADD_NEW_PRODUCT_FAIL'

export const ADD_BILL_SUCCESS = 'ADD_BILL_SUCCESS'
export const ADD_BILL_FAIL = 'ADD_BILL_FAIL'

export const UPDATE_INVENTORY_NUMBER_SUCCESS = 'UPDATE_INVENTORY_NUMBER_SUCCESS'
export const UPDATE_INVENTORY_NUMBER_FAIL = 'UPDATE_INVENTORY_NUMBER_FAIL'
export const PROCESSING_PAYMENT_SUCCESS = 'PROCESSING_PAYMENT_SUCCESS'